### ISSUE TITLE
Make URL paths SEO compliant

### ISSUE THREAD

**Issue by franklywatson** [onflow/cadence-cookbook#8]
When one opens up a cookbook example the link content does not express the content being shown, which to my understanding is bad for SEO

https://cookbook.onflow.org/?preview=13

**Acceptance criteria**

Change links to be SEO friendly: https://cookbook.onflow.org/recipes/admin-resource

**Comment by lealobanov** [comment]
Marking this as closed as this has been implemented in the latest milestone, e.g. https://cookbook.flow.com/token-vault/
